version: '3'

services:
  web:
    image: nginx:latest
    hostname: server
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    hostname: php
    build:
      context: ./docker/php
    volumes:
      - ./:/code
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - messenger
      - database
      - cache
      - mercure

  messenger:
    image: rabbitmq:3.9-management
    hostname: messenger

  database:
    image: mariadb
    hostname: database
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: 12345678
      MARIADB_ROOT_PASSWORD: 12345678
      MARIADB_DATABASE: app
    volumes:
      - ./docker/data/database:/var/lib/mysql

  cache:
    image: redis
    hostname: redis

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    hostname: mercure
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    # Comment the following line to disable the development mode
    # command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config

###< symfony/mercure-bundle ###

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
