version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: symfony-rabbit-mq-playground-server
    hostname: server
    ports:
      - "8081:80"
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: symfony-rabbit-mq-playground-php
    hostname: php
    build:
      context: ./docker/php
    volumes:
      - ./:/code
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - messanger
      - database

  messanger:
    image: rabbitmq:3.9-management
    container_name: symfony-rabbit-mq-playground-messanger
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: mariadb
    container_name: symfony-rabbit-mq-playground-database
    hostname: database
    ports:
      - "33061:3306"
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: 12345678
      MARIADB_ROOT_PASSWORD: 12345678
      MARIADB_DATABASE: app
