index:
  path: /
  controller: App\Controller\DefaultController::index

receiver:
  path: /receiver
  controller: App\Controller\DefaultController::receiver

start_queue:
  path: /start-queue
  controller: App\Controller\DefaultController::startQueue
